// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func ProvideRepository() Repository {
	repository := NewRepository()
	return repository
}

func ProvideService() Service {
	repository := ProvideRepository()
	mainService := NewService(repository)
	return mainService
}

func ProvideServer() *Server {
	mainService := ProvideService()
	server := NewServer(mainService)
	return server
}
